version: 2.1

env: &env
  docker:
    - image: circleci/openjdk:8-jdk
  working_directory: ~/repo

  environment:    
    JVM_OPTS: -Xmx3584M -Xms1024M -Xss16M
    TERM: dumb

jobs:
  build_all:
    parameters:
      version:
        description: "Scala version"
        default: 2.13.3
        type: string
    <<: *env
    steps:
      - checkout
      - run: cat /dev/null | sbt ++${SCALA_VERSION}! clean test publishLocalAll  
      - run:
          command: |
            cd examples
            cat /dev/null | sbt ++${SCALA_VERSION}! compile

workflows:
  build:
    jobs:
      - build_all
          name: 2.12.12
          version: 2.12.12
      - build_all
          name: 2.13.3
          version: 2.13.3

